[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
# language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

# [language-server]
# gherkin-language-server = { command = 'cucumber-language-server', args = ["--stdio"] }

# [[language]]
# comment-token = '#'
# scope = 'source.feature'
# file-types = ['feature']
# indent = { tab-width = 2, unit = ' '}
# language-servers = ['gherkin-language-server']
# name = 'gherkin'
# roots = ['composer.json']

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
nodePath = ""
onIgnoredFiles = "off"
quiet = false
rulesCustomizations = []
run = "onType"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

# [[language]]
# name = "yaml"
# file-types = ["yaml", "yml"]
# config = { yaml = { schemas = { kubernetes = "chart/**/*.yaml"} } }
